// <auto-generated />
namespace WebApplication15.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class intial6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial6));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261035520_intial6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
